//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public int ID { get; set; }
        public byte[] Filerecord { get; set; }
        public string Filetype { get; set; }
        public string Name { get; set; }
    }
}
